# Generated by Django 3.2.21 on 2023-10-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfamily',
            options={'verbose_name_plural': 'product families'},
        ),
    ]
